### ISSUE TITLE
能否考虑与 weixin-robot 项目合并？

### ISSUE THREAD

**Issue by ktmud** [node-webot/wechat#12]
在 @atian25 的大力推广下， `weixin-robot` 模块有了一定的用户量，
也很高兴看到你的中间件关注人数也越来越多。

目前看来，两边做的事情有大部分都是相似的，不同的地方则可以互补。

之前看到你也给 weixin-robot 发过 PR ，不知为何后来还是决定自己写一个呢？

如果觉得代码不符合自己习惯，可以发 PR 来重构嘛，比如 @atian25 就基本把我之前
写的 0.0.x 版本完全重写了。而现在我又删了他很多代码。
如果觉得项目不在自己名下，无法掌控，可以建一个组织来协作嘛。

`weixin-robot` 项目已经分拆成 [weixin-robot](https://github.com/node-webot/weixin-robot)、 [webot-cli](https://github.com/node-webot/webot-cli)、[webot-dashboard](https://github.com/node-webot/webot-dashboard) 三个项目。
计划中这是一整套公共平台API的解决方案，包括命令行工具和一个网页端的后台。

不希望看到更多重复造轮子的事，前端界已经够分裂了。

node 社区也不是没有这样的先例：

比如 [node_mailer](https://github.com/Marak/node_mailer) 就被合并到了 Nodemailer 。

**Comment by huang-1234** [comment]
m
