### ISSUE TITLE
消息体签名及加解密使用报错

### ISSUE THREAD

**Issue by tangsz123** [node-webot/wechat#140]
var config = {
  token: ' my TOKEN',
  appid: 'appid',
  encodingAESKey: ' my encodingAESKey'
};
app.use('/wechat',  wechat(config, function (req, res, next) { 
     if (req.weixin.MsgType == 'text' &&  req.weixin.Content == ‘test’){
                console.log('testlog');
                res.reply('123456');
      }
}))

通过消息体签名加密，我的服务器中能看到日志消息test发出去后打印testlog日志，但是在reply阶段，微信中提示“该公众号暂时无法提供服务，请稍后再试”

**Comment by Laiye** [comment]
-->>>>  appid: 'appid'
'appid'你有没换成自己的。
