### ISSUE TITLE
求教，关于session的问题

### ISSUE THREAD

**Issue by looping84** [node-webot/wechat#151]
场景描述：

    我需要在其他的逻辑页面（比如注册）能获取到用户的基本信息。
    我做的步骤如下：
    1、在/wechat 设置  `req.session.openId = message.FromUserName`
    2、在/reg 获取 `req.session.openId` 然后根据这个openid拿到用户的资料

遇到的问题：

    1、在/wechat设置的req.session，在其他页面访问不到。
    2、/reg 跟/login 这样的页面，设置的session，可以相互访问到

不知道哪里出问题了，请指教，多谢~

**Comment by JacksonTian** [comment]
/wechat 这样的路径是微信的服务器访问的路径。不是用户访问的路径。所以他们的cookie都是不相同的。session当然也不相同了。

**Comment by looping84** [comment]
@JacksonTian  有道理。那我在其他页面，如何获取用户的openid。

**Comment by JacksonTian** [comment]
其他页面走OAuth接口。

**Comment by JacksonTian** [comment]
```
req.sessionStore.get(openid, function (err, data) {
  // todo
});
```

**Comment by looping84** [comment]
@JacksonTian  我看到京东这样的，个人中心里边，没看提示要用户点击 OAuth 授权。能获取到用户的微信号跟头像。

**Comment by JacksonTian** [comment]
京东是腾讯自家的。。。

**Comment by looping84** [comment]
招商银行也是这样。。我以为都可以这样。。

**Comment by JacksonTian** [comment]
应该是有内部合作渠道吧。

**Comment by looping84** [comment]
@JacksonTian 好的，明白了。多谢！我close掉了
