### ISSUE TITLE
使用supertest无法单元测试

### ISSUE THREAD

**Issue by wanglihui** [node-webot/wechat#153]
使用supertest或者curl发送请求到 wechat("sometoken", function(req, res, next){}) 创建的路由时，总是提示超时，具体代码如下:
```
it("should be ok POST /weixin/cb with correct token", function(done) {
    var tail = support.tail("123456");
    var info = {
      sp: "fuck",
      user: 'caohua',
      type: 'event',
      event: 'subscribe'
    }
    request(app)
      .post('/weixin/cb'+tail)
      .send(support.template(info))
      .end(function(err, res) {
        if (err) {
          throw err;
        } else {
          console.info(res.status);
          console.info(res);
          done();
        }
      });
  })
```
返回结果:
```
  1 failing

  1) routes/index.js should be ok POST /weixin/cb with correct token:
     <b>Error: timeout of 2000ms exceeded</b>
      at null.<anonymous> (C:\Users\YCXJ\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:139:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```
测试了几个版本（0.8.11， 0.8.19），均有此问题。代码使用express4.0 + window8

**Comment by wanglihui** [comment]
服务器端代码：
···
var express = require('express');
var router = express.Router();
var wechat = require('wechat');

/* GET home page. */
router.get('/', function(req, res) {
  res.render('index', { title: 'Express' });
});

router.use('/weixin', wechat('123456', function(req, res, next) {
  next();
}));

router.all('/weixin/cb', function(req, res, next) {
  res.reply("test");
});


module.exports = router;
···
貌似是在 wechat/lib/wechat.js 的 load方法中 stream.on('data') stream.on('end') 无法触发，导致callback 一直没有执行

GET 请求正常执行
POST 请求直接卡到哪里

**Comment by wanglihui** [comment]
服务器端代码：
···
var express = require('express');
var router = express.Router();
var wechat = require('wechat');

/* GET home page. */
router.get('/', function(req, res) {
res.render('index', { title: 'Express' });
});

router.use('/weixin', wechat('123456', function(req, res, next) {
next();
}));

router.all('/weixin/cb', function(req, res, next) {
res.reply("test");
});

module.exports = router;
···
貌似是在 wechat/lib/wechat.js 的 load方法中 stream.on('data') stream.on('end') 无法触发，导致callback 一直没有执行

GET 请求正常执行
POST 请求直接卡到哪里

**Comment by wanglihui** [comment]
服务器端代码：
```
var express = require('express');
var router = express.Router();
var wechat = require('wechat');

/* GET home page. */
router.get('/', function(req, res) {
res.render('index', { title: 'Express' });
});

router.use('/weixin', wechat('123456', function(req, res, next) {
next();
}));

router.all('/weixin/cb', function(req, res, next) {
res.reply("test");
});
```
module.exports = router;
貌似是在 wechat/lib/wechat.js 的 load方法中 stream.on('data') stream.on('end') 无法触发，导致callback 一直没有执行

GET 请求正常执行
POST 请求直接卡到哪里

**Comment by JacksonTian** [comment]
我们自己的测试代码不是能正常跑么

发自我的 iPhone

**Comment by wanglihui** [comment]
我用express自己搭建了一个项目，使用supertest 发http请求做单元测试, 发现总是卡死在 stream.on('data‘), stream.on('end')

**Comment by JacksonTian** [comment]
版本，中间件都用对了么

发自我的 iPhone

**Comment by wanglihui** [comment]
使用的测试项目已放到github上， 版本通过npm install wechat --save 安装，应为为最新版本，项目地址:https://github.com/wanglihui/test-req.git 谢谢！

**Comment by JacksonTian** [comment]
还有该问题么
