### ISSUE TITLE
消息体签名及加解密使用报错@v1.2.3

### ISSUE THREAD

**Issue by zppro** [node-webot/wechat#162]
版本1.2.3
明文消息回复OK

使用安全加密后
使用微信公众平台接口调试工具没有问题
但是从客户端微信发起请求就报错
“该公众号暂时无法提供服务，请稍后再试”

调用代码

app.use(wechat(  {
    appid: config.appid, //公众号
    token : config.token, //公众号token
    encodingAESKey:config.encodingAESKey //消息加解密密钥
}, function (req, res, next) {
    res.setHeader('content-type','text/xml');
    var message = req.weixin;
    if (message.FromUserName === 'diaosi') {
        // 回复屌丝(普通回复)
        res.reply('hehe');
    } else if (message.FromUserName === 'text') {
        //你也可以这样回复text类型的信息
        res.reply({
            content: 'text object',
            type: 'text'
        });
    } else if (message.FromUserName === 'hehe') {
        // 回复一段音乐
        res.reply({
            type: "music",
            content: {
                title: "来段音乐吧",
                description: "一无所有",
                musicUrl: "http://mp3.com/xx.mp3",
                hqMusicUrl: "http://mp3.com/xx.mp3",
                thumbMediaId: "thisThumbMediaId"
            }
        });
    } else {
        // 回复高富帅(图文回复)
        //res.reply([
        //    {
        //        title: '你来我家接我吧',
        //        description: '这是女神与高富帅之间的对话',
        //        picurl: 'http://nodeapi.cloudfoundry.com/qrcode.jpg',
        //        url: 'http://nodeapi.cloudfoundry.com/'
        //    }
        //]);
        res.reply('hello world!!!');

    }
}));

------------------------------请求的消息报文----------------------------------
POST /?signature=31b6d8f9061ef21267fefbfc0775f842615e9ba7&timestamp=1427442195&nonce=1862379936&encrypt_type=aes&msg_signature=3c1d9c19b74cdcc1f26ca4b4bfa72864a64826ba HTTP/1.1
Host: wx.ngrok.lifeblue.com.cn:49999
User-Agent: Mozilla/4.0
Content-Length: 534
Accept: */*
Cache-Control: no-cache
Connection: close
Content-Type: text/xml
Pragma: no-cache
Accept-Encoding: gzip

<xml>
    <ToUserName><![CDATA[gh_f47f32f03e15]]></ToUserName>
    <Encrypt><![CDATA[QyIxrTJxE5nVfS+eF/cW06MqF/HFp03+ncZG6PESoFmAOn4PpvAn1soV0xLEoto8priIIzd3/ibO0EvhhLAW+aSTeJMbvwPHJY6Ur7P4/7+I5yGmOjOqxZ/VeTv9kfXu1GZyFwfnnDLnWOiqakhS02RSXYPh27BqbTGzrUktQQkVJLX+AvCBuCz6DMerB1QFXFqagnulHybYPLYjKCqd1ywL4fQPJkpDJvaDj84lyjJYzQZKbjXbNEcnmXI2a3FfSSKh22OmjIPwC3cWsSUcyKncppTfVddftYfGINVslrduXVh+t7SY9hiPtyg/YmZNrC+NP557+O2SUdm4/Y9QdXGXo8gEa/zWhGBODBm/dKT1q61ZHiWpVO2eWfdl6rpbzFKR7q8VMTIzoe9vrhbFHVBsmBuXIFK/cw82RYaN86c=]]></Encrypt>
</xml>

------------------------------返回的消息报文----------------------------------
HTTP/1.1 200 OK
Connection: close
Content-Length: -1
Content-Type: text/xml
Date: Fri, 27 Mar 2015 07:43:15 GMT
X-Powered-By: Express

<xml><Encrypt><![CDATA[7/71yCB3vyZI4TLem4K3mutIsE32y5FHKf/WCLRGMPSwjAgXqmzxjQDnCvzCQC2w03Za8FK3XmnGzCCg9UjsZHA5d7PeBe5ZadOplrq40LG4W1qyT1+6V7vm3NGGwhX6qvvcYbX812VuIkNYmDVa/0eTYCSNiiRjpEvr5E+q6rLBfcZ0WsQt5yDFQgLpiwS9JTbQtF2dYYBFVqoXujwn9rB0r+0ZAfT5IPAavCVx/m6wgfN60eXJF9IHtqRwcHLLhaOV9EVO0R+jFccYLsnp0pzPWoABJeUtpb5BwLJCCJYL9Vl7eiBik0sBo4QNVEJXMcCWivQn3Qh2/4hKtCUDt4lo1PWym0zjp+FwhNUz3SN7eYZ9oeRJ+Fa38jcxGBZG]]></Encrypt><MsgSignature><![CDATA[1da57eeb610ddb1d349dc333a4bd59cd0c3dba9c]]></MsgSignature><TimeStamp>1427442195494</TimeStamp><Nonce><![CDATA[87768119270]]></Nonce></xml>

**Comment by JacksonTian** [comment]
响应有问题吧。

**Comment by zppro** [comment]
从头到尾，响应代码就是res.reply('hello world!!!');这句
其他都是类库中间件包装输出的。

**Comment by zppro** [comment]
现在搞不明白的就是明文和TECENT自带的调试接口都是OK的。就变成密文的时候报错

**Comment by JacksonTian** [comment]
还有问题么。

**Comment by mrlong** [comment]
反正我没有成功，我查看文档明文写 wechat(config.wechat.token,funciont(req,res,next)(){}),
加密写： wechat(config.wechat,funciont(req,res,next)(){})。
