### ISSUE TITLE
请问 网页授权获 有没有api .谢谢。

### ISSUE THREAD

**Issue by mrlong** [node-webot/wechat#165]
http://mp.weixin.qq.com/wiki/17/c0f37d5704f0b64713d5d2c37b468d75.html#.E7.AC.AC.E4.BA.8C.E6.AD.A5.EF.BC.9A.E9.80.9A.E8.BF.87code.E6.8D.A2.E5.8F.96.E7.BD.91.E9.A1.B5.E6.8E.88.E6.9D.83access_token

**Comment by JacksonTian** [comment]
搜wechat-oauth

发自我的 iPhone

**Comment by mrlong** [comment]
谢谢，我找到了。但我在用页面授权时，无法取到code ,  
我是这样处理：
   1. 开发设置了 url , 这个url 是我填参数，并转向的url
   2. https://open.weixin.qq.com/connect/oauth2/authorize?appid=xxxxxxxxxxxxxx&redirect_uri=http%3A%2F%2Fhdl.mrlong.cn%2Fm&response_type=code&scope=snsapi_base&state=#wechat_redirect

  4.  我在node 内使用：  var code = req.query.code  , 这个值一直取不出来。

**Comment by JacksonTian** [comment]
express用了么。

**Comment by mrlong** [comment]
已解决了。是重定向的问题。谢谢了。
