### ISSUE TITLE
接收vocie消息数据Recognition字段为空的问题

### ISSUE THREAD

**Issue by nodeweb** [node-webot/wechat#167]
接收微信voice类型消息，在微信公众平台后台开启“语音识别功能”后，可以看到返回数据里面有Recognition字段，但是值总是为空。

----------------------app里面代码-------------------

app.use('/wechat', wechat(config, function (req, res, next) {
  // 微信输入信息都在req.weixin上
  var message = req.weixin;
  var xml  = req.weixin_xml;
  //微信服务号开启语音识别后监听voice
  if( message.MsgType == 'voice' ){
      console.log('message=' , message);
      res.reply({
            content: '接收语音识别结果！',
            type: 'text'
      });      
  };
  }));

------------------------打印message的结果----------------------------------

message= { ToUserName: 'gh_2ae8ade98f9a',
  FromUserName: 'oGT7Ushb6TF79A2WOy4fF-zPmkMU',
  CreateTime: '1430724729',
  MsgType: 'voice',
  MediaId: '2JbGOr78-KnFkgrmFzeu9P0H8zt-1uFm1FMKzpDliD4Qvev-Kx3U_LYEpdnD--2B',
  Format: 'speex',
  MsgId: '6144915920633462784',
  Recognition: '' }   //----测试很多状况的语音内容，这个值都是空值

=======打印XML发现问题所在了所在了，分两种情况=========

------------如果返回的XML里面的Format=speex----- ###这种情况Recognition为空
msg= { ToUserName: 'gh_2ae8ade98f9a',
  FromUserName: 'oGT7Ushb6TF79A2WOy4fF-zPmkMU',
  CreateTime: '1430725104',
  MsgType: 'voice',
  MediaId: 'OEApMxIWMk_xtcshDGMkTc0aWbj-XVWFLxNbbpytJRnTRLpO7SbZq_s_IAVs2dei',
  Format: 'speex',
  MsgId: '6144917531246198784',
  Recognition: '' }

-----------------如果返回的XML里面的Format=amr-----###这种情况Recognition正确识别
msg= { ToUserName: 'gh_2ae8ade98f9a',
  FromUserName: 'oGT7Ushb6TF79A2WOy4fF-zPmkMU',
  CreateTime: '1430725284',
  MsgType: 'voice',
  MediaId: 'dLGUWkX0dX_uCKd5QGwaBiuBqPuwoXIkZ_oUx0-foMHb34BmR_MMHI1Usalx64Jp',
  Format: 'amr',
  MsgId: '6144918304340312064',
  Recognition: '你好你好' }

**Comment by JacksonTian** [comment]
看看原始xml数据是怎样的。打印下req.weixin_xml看看。

**Comment by nodeweb** [comment]
打印XML发现问题所在了所在了，分两种情况:

------------如果返回的XML里面的Format=speex----- ###这种情况Recognition为空
xml= <xml><ToUserName><![CDATA[gh_2ae8ade98f9a]]></ToUserName>
<FromUserName><![CDATA[oGT7Ushb6TF79A2WOy4fF-zPmkMU]]></FromUserName>
<CreateTime>1430725319</CreateTime>
<MsgType><![CDATA[voice]]></MsgType>
<MediaId><![CDATA[y9f6qIp9JmDY4FpUs6ZId0Us8WORATWzw24J5aLQCoy--83w7qnPACFNe65vL76r]]></MediaId>
<Format><![CDATA[speex]]></Format>
<MsgId>6144918454664167424</MsgId>
<Recognition><![CDATA[]]></Recognition>
</xml>

-----------------如果返回的XML里面的Format=amr-----###这种情况Recognition正确识别
xml= <xml><ToUserName><![CDATA[gh_2ae8ade98f9a]]></ToUserName>
<FromUserName><![CDATA[oGT7Ushb6TF79A2WOy4fF-zPmkMU]]></FromUserName>
<CreateTime>1430725284</CreateTime>
<MsgType><![CDATA[voice]]></MsgType>
<MediaId><![CDATA[dLGUWkX0dX_uCKd5QGwaBiuBqPuwoXIkZ_oUx0-foMHb34BmR_MMHI1Usalx64Jp]]></MediaId>
<Format><![CDATA[amr]]></Format>
<MsgId>6144918304340312064</MsgId>
<Recognition><![CDATA[你好你好]]></Recognition>
</xml>

**Comment by JacksonTian** [comment]
是格式的原因对吧？

**Comment by nodeweb** [comment]
不是。是微信语音识别本身的问题。
现在很多带口音的发音、发音过快等等微信还不能很好的识别，然后微信返回Format=speex 。
识别不了或者是没有声音的微信都会返回Format=speex。
看来微信这个功能还不能太期待。
