### ISSUE TITLE
connect.query 有问题

### ISSUE THREAD

**Issue by pasicopan** [node-webot/wechat#173]
var connect = require('connect');
错误信息：
app.use(connect.query()); // Or app.use(express.query());

TypeError: Object function createServer() {
  function app(req, res, next){ app.handle(req, res, next); }
  merge(app, proto);
  merge(app, EventEmitter.prototype);
  app.route = '/';
  app.stack = [];
  return app;
} has no method 'query'

**Comment by JacksonTian** [comment]
自己安装 querystring 解析的中间件即可。

**Comment by pasicopan** [comment]
下面这样可以了
var connect = require('connect');
var querystring = require('querystring');

app.use(express.query());

**Comment by JacksonTian** [comment]
我决定把示例改成express的。免得每人都来问 connect没有query的问题。
