### ISSUE TITLE
menu 在这个项目中是否是多余的？

### ISSUE THREAD

**Issue by VectorHo** [node-webot/wechat#179]
如题，我看wechat-api支持menu功能

**Comment by nick-ma** [comment]
何来多余一说？
这个是创建自定义菜单用的接口。

2015-06-10 11:11 GMT+08:00 Vector Ho <notifications@github.com>:

**Comment by JacksonTian** [comment]
当时的一个想法，将callback和menu里的key关联起来。最终没有实现，createMenu也拆分到wechat-api里了。PR welcome。

**Comment by VectorHo** [comment]
谢谢

**Comment by JacksonTian** [comment]
menu文件已经移除。
