### ISSUE TITLE
关于用户获取oauth，经常出错。

### ISSUE THREAD

**Issue by looping84** [node-webot/wechat#184]
我现在的逻辑是这样的，求指点，布置多核的时候，经常报错（ { [WeChatAPIError: invalid code] name: 'WeChatAPIError', code: 40029 }）。

感觉是code被重复使用了。session我已经存到redis里了。
    
    var client = new OAuth();
      if (req.session.openId) {
        next();
    } else { //需要授权
        if (req.query.code) {
          
            client.getAccessToken(req.query.code, function(err, result) {
                if (err) {
                    //这里会抛出40029的错误
                    return;
                }
                req.session.openId = result.data.openid;
                client.getUser(result.data.openid, function(err, result) {
                    if (err) {
                        return;
                    }
                    req.session.userInfo = result;
                    res.redirect(redirectUrl);
                });
                return;
            });
        } else {
            var authUrl = client.getAuthorizeURL(redirectUrl, 'wx', 'snsapi_userinfo');
            res.redirect(authUrl);
        }
        return;
    }

**Comment by JacksonTian** [comment]
部署多实例请使用外部存储。构造client时传入getToken和saveToken函数

发自我的 iPhone

**Comment by looping84** [comment]
@JacksonTian  已经传进去了，这里没写，用的redis。

    var client = new OAuth(config.weixin.appid, config.weixin.secret, function(openid, callback) {
    redisClient.get("weixinAccessToken:" + openid, function(err, reply) {
        if (err) {
            console.log(err);
            return callback(err);
        }
        callback(null, JSON.parse(reply));
     })
      }, function(openid, token, callback) {
    // 请将token存储到全局，跨进程、跨机器级别的全局，比如写到数据库、redis等
    // 这样才能在cluster模式及多机情况下使用，以下为写入到文件的示例
    // 持久化时请注意，每个openid都对应一个唯一的token!
     redisClient.set("weixinAccessToken:" + openid, JSON.stringify(token), function(err, reply) {
        console.log("存openid到redis", err, reply);
        callback(null)
     })
    });


如果redis读写都正常，我提问的那段**if (req.query.code) {}**逻辑对吗？
