### ISSUE TITLE
关于用户授权，分享url的问题

### ISSUE THREAD

**Issue by looping84** [node-webot/wechat#185]
1、A页面（比如登录页面）需要拿用户授权
2、redirect到微信服务器，用户点击同意授权，跳回A页面。但此时，会有**code=xxxxx**的参数。
3、点击分享，把此页面分享到朋友圈，此时分享出去的页面带有，code参数。
4、当另外一个用户**小朴**点击带code参 数的这个连接的时候，因为有code，但是这个code已经被上个用户使用过一次。此时调用  ` auth.getUserByCode(req.query.code)` 会出问题，报错，请问如何解决？
代码如下
```javascript
  if (req.query.code) {
            client.getUserByCode(req.query.code, function(err, result) {              
                if (err) {
                    console.log("获取用户信息出错", err)
                    return;
                }
                             
                req.session.userInfo = result;
                
                next();
            })
```

**Comment by nick-ma** [comment]
方法一：使用jssdk，在页面里写上分享时候的回调函数，在里面重新指定分享出去的url。但这个方法由于收到jssdk的限制，成功率不是太高，尤其是网络不好的时候，会影响到分享的动作。
方法二：前端使用history api， history.replaceState 方法，把当前的window.location.href 中的code去掉。

**Comment by looping84** [comment]
@nick-ma 方法一貌似不可以，微信要求jssdk传进去的url必须保持一致。
第二种，code是参数，不是hash，貌似也不行

**Comment by triunity** [comment]
分享的时候就应该屏蔽掉code，不应该带着code分享出去。

**Comment by navyxie** [comment]
既然接入了微信  jsapi ,那么你就可以控制分享出去的链接，如果不想用户分享当前带code的链接，你就设置成另一个就可以了。

**Comment by looping84** [comment]
@navyxie 微信的分享url必须跟服务器配置的是一样的。

**Comment by looping84** [comment]
最后在授权的中间件，把code参数去掉，解决了。

**Comment by NoraGithub** [comment]
请问授权中间件 是什么意思呢？@looping84
