### ISSUE TITLE
关于session的问题。

### ISSUE THREAD

**Issue by mrlong** [node-webot/wechat#186]
我在做一个网站二维扫一扫登录功能：
     1. 进入网站，判定session (我暂定为A) 有没有值，如有值是直接进入主页。
     2. 如session (A) 没有值则调用api 生成临时二维码，并给id值=10000. 将img 图转到页面用户扫。
     3. 用户扫了之后会有事件，取出openid 校对成功之后我向req.session 写openid ，这时的session （我暂定为B）,同时也写了wxsession 。

问题出现了：
    session (A)   、session (B)  wxsession 三个保存sessionStore 都不一样。 我回到网站时无法取出openid 的值。

https://cnodejs.org/topic/55a476513ecc81b621bba81b#55a486313ecc81b621bba849

**Comment by JacksonTian** [comment]
用wechat-oauth的登陆吧。

**Comment by mrlong** [comment]
pc 采用扫一扫微信登录，是涉及到两个端 一个是pc浏览器，及微信端。 按原理
必然会生成两个不同的sessionID。

唯一的交点就是pc生成的二维码怎么与微信端扫后关联起来。 我查了node-wechat 的api 生成临时的qrcode 只有保存
场景id (int 型) 不是string , 无将sessionID 转到微信端。

**Comment by JacksonTian** [comment]
其实无论什么场景，你只要拿到openid，将数据存储下来。不管是什么端，openid一样，就是相同的用户。
