### ISSUE TITLE
如何转发接收到的message到自己的微信上，或者某个关注者的微信上，或者通知自己？

### ISSUE THREAD

**Issue by vonnyfly** [node-webot/wechat#187]

**Comment by JacksonTian** [comment]
调用模版消息将内容转发到自己微信呗

**Comment by vonnyfly** [comment]
能不能说详细点？

**Comment by vonnyfly** [comment]
能给点详细提示？
收到的消息通知自己，包含作者内容信息。

res.reply只是回复


2015-08-24 10:02 GMT+08:00 Jackson Tian <notifications@github.com>:

> 调用模版消息将内容转发到自己微信呗
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/node-webot/wechat/issues/187#issuecomment-133989730>.
>



-- 
Thanks and Best Regards,
Feng Li(Alex)

**Comment by JacksonTian** [comment]
看 wechat-api

**Comment by nick-ma** [comment]
把通过回调接口收到的消息保存好，然后拼装成一个模版消息，用主动调用接口发送给指定的人（比如：你自己），over。
