### ISSUE TITLE
sending multiple replies to one user question

### ISSUE THREAD

**Issue by dcsan** [node-webot/wechat#189]
when a user sends a chat to an official account, we have a short period to reply.

but is it possible for one question, for the account to send multiple replies? eg

```
user: menu
app: we have two options, red or blue.
app: [image: red]
app: [image: blue]
app: which one do you want, red or blue?
```

if it is possible, how would we do it with your current API?
your API design is very much `request -> response` 

is there a way to `res.reply() ` twice? perhaps using `next` ?

**Comment by JacksonTian** [comment]
Your can call res.reply() to answer user as first reply, the other replies must be answered with custom message. see http://mp.weixin.qq.com/wiki/1/70a29afed17f56d537c833f89be979c9.html#.E5.AE.A2.E6.9C.8D.E6.8E.A5.E5.8F.A3-.E5.8F.91.E6.B6.88.E6.81.AF

**Comment by dcsan** [comment]
thanks for your reply!

I see from the incoming `request.query` we get:

```
{ 
  signature: 'db3e07b661a86b1cea7daeeXXXXXXXXX',
  timestamp: '1442169xxx',
  nonce: '52837xxx' 
}
```

can that signature be used as an ACCESS_TOKEN to send another message?

are there any helper functions/APIs in your package for sending messages without using the `req.reply()` method?

**Comment by JacksonTian** [comment]
you can see `wechat-api` module for the wechat's API.
