### ISSUE TITLE
List回复不支持Session？

### ISSUE THREAD

**Issue by notechsolution** [node-webot/wechat#191]
您好，灰常感谢你们提供的wechat，老感谢了！我们用了wechat 2.0.2，部署在多节点的nodejs，session存放在db。发现如果用户回复List的内容被派到另外一个节点的时候，该节点的List取不到之前定义的列表，导致响应不正确。目测List没有放在session里面，而是一个静态类，请问 对于List的描述有没有错？ 在readme的描述中，“等待回复，类似于电话拨号业务。该功能在WXSession的基础上提供”，List应该在session的。 请问有没有什么解决方法？或者修改计划？谢谢

**Comment by JacksonTian** [comment]
需要用req.wxsession

**Comment by notechsolution** [comment]
req.wxsession已经用了，但多节点还是不行。是不是需要把List的对象放到wxsession里面？但貌似List对象是静态类

**Comment by notechsolution** [comment]
已经在List 和 wechat添加响应的方法，可以支持到List在跨节点的环境下可用。具体改动加到分支 “List_cross_node_patch” 里面。
