### ISSUE TITLE
[Bug] 等待回复 即使wxsessionList 在redis中，List本身保存在内存，无法共享

### ISSUE THREAD

**Issue by wenwei1202** [node-webot/wechat#202]
具体的错误如下：
worker:5  TypeError: Cannot call method 'get' of undefined
worker:5    at done (/usr/src/app/node_modules/wechat/lib/wechat.js:270:27)
worker:5   at /usr/src/app/node_modules/wechat/lib/wechat.js:331:9
错误原因：
wxsession是在redis里，所以判断条件为true，
if (message.MsgType === 'text' && req.wxsession && req.wxsession._wait) 
但是list的add是在之前的worker：
var list = List.get(req.wxsession._wait);
list返回为null，单核cpu没有问题，多核情况下必定报错
解决方法：
序列化List 对象到wxsession ？

**Comment by JacksonTian** [comment]
list需要应用启动就初始化好。

**Comment by wenwei1202** [comment]
我用的是strongloop， 在boot中初始化了List，但是发现在cluster每个worker，都初始化了一份List，这样就仍然无法共享，刚学node几个月，只读了你的本书，所以还不是特别理解node。初始化在boot中，应该是对的吧？还是说是在在boot前就初始化？

2015-11-04T10:00:14.036Z pid:19207 worker:3 init list>>>>>>>>>
2015-11-04T10:00:14.060Z pid:19203 worker:1 init list>>>>>>>>>
2015-11-04T10:00:14.243Z pid:19205 worker:2 init list>>>>>>>>>
2015-11-04T10:00:14.256Z pid:19209 worker:4 init list>>>>>>>>>

**Comment by wenwei1202** [comment]
上面表述的有点问题，如果这样的话，是初始化之后list就不能做任何修改了，如果不修改的话，没有问题，但是如果修改的话会问题了，例如再次用List.add()

**Comment by wenwei1202** [comment]
这个不是bug，只是List不支持动态添加而已，现在关闭

**Comment by JacksonTian** [comment]
https://github.com/node-webot/wechat/pull/198 有同学提交了一个支持动态修改的PR。对序列化和反序列化部分还持观望。可以一起看看

**Comment by wenwei1202** [comment]
刚看了这个PR，和我当时第一反应一样，这样做能解决问题，但是太不优雅了，session里面大量的被序列化的代码，而且会出现大量不必要的拷贝，这样的序列化对一个公共的组件肯定是行不通的。最好的办法是进程间直接同步，不过不现实，所以序列化是必须的，但是保存绝对不能在session里，应该类似AccessToken一样，序列化之后，存储方式由外部来提供，需要时在从外部取回反序列化。这样就可以减少无谓的拷贝。 当然这种做法会有个时间差的问题，即用户收到选项列表到当服务器收到这段时间里，List被修改了，可能会出现问题。这个就需要牵扯到验证时间戳，将过期List保留一段时间再失效。
