### ISSUE TITLE
Wrong format in video callback message

### ISSUE THREAD

**Issue by steve-p-com** [node-webot/wechat#209]
Greetings from the UK :smile:

I have had great success with this awesome wechat module in a server that I am currently developing. However, I have found one small problem. It occurs when replying to a callback message with video content. The API documentation says that the reply message should look like this:

```
<xml>
  <ToUserName><![CDATA[toUser]]></ToUserName>
  <FromUserName><![CDATA[fromUser]]></FromUserName>
  <CreateTime>12345678</CreateTime>
  <MsgType><![CDATA[video]]></MsgType>
  <Video>
    <MediaId><![CDATA[media_id]]></MediaId>
    <ThumbMediaId><![CDATA[thumb_media_id]]></ThumbMediaId>
  </Video> 
</xml>
```

That agrees with the documentation for this module, which says that to reply with a video, you do this:

```
res.reply({
  type: "video",
  content: {
    mediaId: 'mediaId',
    thumbMediaId: 'thumbMediaId'
  }
});
```

Unfortunately, this does not work at the moment.

In wechat.js, the template for a video message looks like this:

```
'<% } else if (msgType === "video") { %>',
    '<Video>',
      '<MediaId><![CDATA[<%-content.mediaId%>]]></MediaId>',
      '<Title><![CDATA[<%-content.title%>]]></Title>',
      '<Description><![CDATA[<%-content.description%>]]></Description>',
    '</Video>',
```

I think it should probably say something like:

```
'<% } else if (msgType === "video") { %>',
    '<Video>',
      '<MediaId><![CDATA[<%-content.mediaId%>]]></MediaId>',
      '<ThumbMediaId><![CDATA[<%-content.thumbMediaId%>]]></ThumbMediaId>'
    '</Video>',
```

**Comment by steve-p-com** [comment]
Just to add: The English language README.en.md says that you reply like this:

```
res.reply({
  type: "video",
  content: {
    mediaId: 'mediaId',
    thumbMediaId: 'thumbMediaId'
  }
});
```

But the main README.md says this:

```
res.reply({
  type: "video",
  content: {
    title: '来段视频吧',
    description: '女神与高富帅',
    mediaId: 'mediaId'
  }
});
```

I am assuming that the English language version is correct, because the documentation here agrees with it:

http://admin.wechat.com/wiki/index.php?title=Callback_Messages#Video_Message

I have tried replying using the existing version that contains description and title but no thumbMediaId and it doesn't work. The reply message is accepted by WeChat but never reaches the original user. So I assume that the version that contains only mediaId and thumbMediaId is the one that we should be using?

**Comment by JacksonTian** [comment]
http://admin.wechat.com/wiki/index.php?title=Callback_Messages#Video_Message English version
http://mp.weixin.qq.com/wiki/18/c66a9f0b5aa952346e46dc39de20f672.html#.E5.9B.9E.E5.A4.8D.E8.A7.86.E9.A2.91.E6.B6.88.E6.81.AF Chinese version.

Oh my god, the official documents are difference.

**Comment by steve-p-com** [comment]
Hmmm. That means we really don't know which of the two versions is correct.

I have tested replying with both formats. Neither seems to work as expected, as the original user does not receive the reply. So perhaps both of the documented versions are wrong, or video replies are broken in the WeChat server.

**Comment by pampanelson** [comment]
toast to wechat api doc for thouands times!
