### ISSUE TITLE
为什么有的图片消息会重复收到两次?

### ISSUE THREAD

**Issue by keel** [node-webot/wechat#213]
有时发送一张图片时,会收到两个同样的回调, msgId都是一样的.
这种情况不是每次必现, 但在`).image(function(message, req, res, next) {` 后面直接打印message的log,就能看到.

**Comment by XGHeaven** [comment]
这应该是微信的策略，[wechat-wiki](http://mp.weixin.qq.com/wiki/1/6239b44c206cab9145b1d52c67e6c551.html)

> 微信服务器在将用户的消息发给公众号的开发者服务器地址（开发者中心处配置）后，微信服务器在五秒内收不到响应会断掉连接，并且重新发起请求，总共重试三次，如果在调试中，发现用户无法收到响应的消息，可以检查是否消息处理超时。关于重试的消息排重，有msgid的消息推荐使用msgid排重。事件类型消息推荐使用FromUserName + CreateTime 排重。

**Comment by keel** [comment]
那估计是图片比较大,上传后服务端会有一个下载时间,超过5秒了,所以导致重发.
重排加入后应该可以解决,多谢.
