### ISSUE TITLE
为啥不支持restify框架呢

### ISSUE THREAD

**Issue by niefengjun** [node-webot/wechat#223]
为啥不支持restify框架呢

**Comment by nick-ma** [comment]
作者不用restify，你可以自己实现一套。

2016-02-18 13:56 GMT+08:00 niefengjun <notifications@github.com>:

**Comment by JacksonTian** [comment]
想要支持的话 也很容易，不过我暂时没有时间去写。

**Comment by mdreamfly** [comment]
@JacksonTian  给个思路，我来写
