### ISSUE TITLE
依赖包的问题

### ISSUE THREAD

**Issue by sunsnow8** [node-webot/wechat#228]
node 版本是0.10.21

失败原因：编译失败
失败信息：Fix depends failed. Please check requirements.txt or package.json.

npm ERR! fetch failed http://registry.cnpmjs.org/xmlbuilder/download/xmlbuilder-8.2.1.tgz
npm ERR! fetch failed http://registry.cnpmjs.org/xmlbuilder/download/xmlbuilder-8.2.1.tgz
npm ERR! fetch failed http://registry.cnpmjs.org/xmlbuilder/download/xmlbuilder-8.2.1.tgz
npm ERR! Error: CERT_UNTRUSTED
npm ERR! at SecurePair.<anonymous> (tls.js:1356:32)
npm ERR! at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR! at SecurePair.maybeInitFinished (tls.js:968:10)
npm ERR! at CleartextStream.read [as _read] (tls.js:462:15)
npm ERR! at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR! at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR! at doWrite (_stream_writable.js:221:10)
npm ERR! at writeOrBuffer (_stream_writable.js:211:5)
npm ERR! at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR! at write (_stream_readable.js:583:24)
npm ERR! at flow (_stream_readable.js:592:7)
npm ERR! at Socket.pipeOnReadable (_stream_readable.js:624:5)
npm ERR! If you need help, you may report this log at:
npm ERR! <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR! <npm-@googlegroups.com>
npm ERR! System Linux 3.10.1-grsec
npm ERR! command "/home/bae/bae/node-v0.10.21-linux-x64/bin/node" "/home/bae/bae/node-v0.10.21-linux-x64/bin/npm" "install" "--production"
npm ERR! cwd /home/bae/run/baeng/helios/work/appidzd02vr736k/.bae
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR! /home/bae/run/baeng/helios/work/appidzd02vr736k/.bae/npm-debug.log
npm ERR! not ok code 0

**Comment by XGHeaven** [comment]
这个可能是网络问题，一开始 fetch failed...

**Comment by JacksonTian** [comment]
try again.
