### ISSUE TITLE
可以做到只处理来自微信公众平台的接口吗?

### ISSUE THREAD

**Issue by JamesKarl** [node-webot/wechat#240]
如果是用express目前的设计没有问题. 如果是用sails会有问题.

比如我现在的配置如下(config/http.js/middleware/order):
```
order: [
       'startRequestTimer',
       'cookieParser',
       'session',
       'myRequestLogger',
       'bodyParser',
       'handleBodyParserError',
       'compress',
       'methodOverride',
       'poweredBy',
       '$custom',
       'router',
       'www',
       'favicon',
       'wechatProcessor', // 微信中间件在这里配置
       '404',
       '500'
     ],
```

当收到request后,会顺次执行order数组中的中间件. 如果检查签名失败, wechat内部会执行
```
res.writeHead(401);
res.end('Invalid signature');
```
优先级比wechatProcessor 低的中间件永远得不到执行. 这不是想要的结果.
```
wechatProcessor: wechat(
      {
        appid: 'xxx',
        token: 'xxx',
        encodingAESKey: 'xxx',
      }, function(req, res, next) {
        if (req.path.match(sails.config.wechat.wechatPath)) {
          WechatService.onReceiveMessage(req, res);
        } else {
          next();
        }
      }),
```
可不可以再wechat初始化是添加一个选项,发现签名失败流程可以继续往下走,而不是直接返回401错误,提示"Invalid signature". 发现签名认证失败后可以执行:
```
res.next();
```
或者在weichat内部只处理来自微信公众平台的请求.

感谢大力支持

**Comment by JacksonTian** [comment]
前面加路由不就好了吗

**Comment by JamesKarl** [comment]
sails 的路由是在config/routes.js中配置的， path指向view or Controller.action.不是middleware. wechat作为一个middleware要在config/http.js/middleware/order中配置。  

express添加路由时指定的就是middleware. sails和express不一样

**Comment by JacksonTian** [comment]
那你再研究下怎么设置路由

**Comment by JamesKarl** [comment]
我知道怎么设置路由，就是按照以下官方文档做的呀
http://sailsjs.org/documentation/concepts/middleware
Express Middleware In Sails
#

One of the really nice things about Sails apps is that they can take advantage of the wealth of already-existing Express/Connect middleware out there. But a common question that arises when people actually try to do this is:

    "Where do I app.use() this thing?".

In most cases, the answer is to install the Express middleware as a custom HTTP middleware in sails.config.http.middleware. This will trigger it for ALL HTTP requests to your Sails app, and allow you to configure the order in which it runs in relation to other HTTP middleware.
