### ISSUE TITLE
无法适用于 微信第三方平台 吗

### ISSUE THREAD

**Issue by foxtail000** [node-webot/wechat#244]
router.use '/msgappid/:appid',(req, res, next) ->
  cfg =
    token: config.wxthr.token
    appid: req.params.appid
    encodingAESKey: config.wxthr.encodingASEkey
  console.log cfg
  wechat(cfg, (req,res,next) ->
    message = req.weixin
    console.log message
    res.reply '联系客服'
  )

错误打印

{ signature: '218d1f2e617d750b52e9753ea99dff9db1604dc4',
  timestamp: '1470744579',
   nonce: '1977651996',
   openid: 'oZQ1EwWPBYJvfxTYPk9Tiku01Vpg',
  encrypt_type: 'aes',
  msg_signature: '452aca2459513e83b4cc424fcbb57b97a72e4c03' }
[Error: please check arguments]

我觉得应该是能兼容的。  - -. 应该是我哪里没用对

**Comment by JacksonTian** [comment]
微信第三方平台是什么意思？

**Comment by MarcoPai** [comment]
https://open.weixin.qq.com/
