### ISSUE TITLE
对请求进行校验时有些情况中间件能否不终结请求

### ISSUE THREAD

**Issue by U9XXL** [node-webot/wechat#255]
请求中如果没有携带signature、timestamp、nonce和echostr四个特征参数时，肯定不是来自微信服务器，能否不终结请求而是调用 next() 方法将控制权交给下一个中间件？

**Comment by JacksonTian** [comment]
你可以在前面加中间件来处理。如果有4个参数，next交给wechat，如果没有，自己处理。
