### ISSUE TITLE
如果没有指定图片或其它类型的处理，会不会执行 express 的下一个路由？

### ISSUE THREAD

**Issue by memstone** [node-webot/wechat#265]
app.use('/wx', wechat(wx_config, wechat.text((message, req, res, next) => {
    res.reply([{title:'demo', 
    description:'skdkd',
    picurl:'http://images.csdn.net/20170322/no1.jpg',
    url:'http://geek.csdn.net/news/detail/188258'
    }]);
}).event((message, req, res, next)=>{
    console.log('evet...');
    console.log(message);
    res.reply('hello event.');
})));

app.get('/wx', (req, res) => {
    console.log('not processed.');
    res.reply('Your message not supported yet.');
});

以上的代码，不会执行 app.get，需要怎么编码？

**Comment by nick-ma** [comment]
The GET method can only be invoked once when you activated the Callback
Mode at the Wechat console.
However, all the callback actions that wechat server performs use POST
method.

2017-03-23 14:51 GMT+08:00 memstone <notifications@github.com>:

**Comment by memstone** [comment]
@nick-ma  thank u very much.
after change GET to POST, then it works.

**Comment by nick-ma** [comment]
You are welcome and issue closed.
