### ISSUE TITLE
[建议] res.reply(content) 改为 res.reply(content).end() 以支持一个http请求过程中回发多条消息

### ISSUE THREAD

**Issue by yi** [node-webot/wechat#271]
[建议] res.reply(content) 改为 res.reply(content).end() 以支持一个http请求过程中回发多条消息

### 理由
 1. 目前的 res.reply 实现只能回发一条消息。 因为 `content` 被发掉后，[res.end 了](https://github.com/node-webot/wechat/blob/master/lib/wechat.js#L272)
 1.  一个微信主动消息的回话过程，只完全可以回发多条消息的。在一些特定的情况下，这个需求很强烈。

### 建议修改

将 res.reply() 的语法签名，改成 res.reply().end() 即将  `reply()` 和 `end()` 分开。由开发者决定是否接受会话。

**Comment by yi** [comment]
just ignore

**Comment by JacksonTian** [comment]
还有这种操作啊

**Comment by yi** [comment]
恩恩。看了一下源代码，感觉用的express api 可能有点老。
看一下 express api v 4.x 。有些操作可以做的更加灵活一点

**Comment by nick-ma** [comment]
估计是被某些公终号的行为给骗了吧。


2017-08-04 21:54 GMT+08:00 Jackson Tian <notifications@github.com>:

**Comment by yi** [comment]
response 本来就是一个 writable steam 呀

**Comment by JacksonTian** [comment]
response的行为我应该比你清楚，但你要详细看下微信的文档，你只有回复或者不回复的选择，没有两次回复的能力。

回复多条信息的能力在 wechat-api 中，那个跟 express 并无关系了。

**Comment by yi** [comment]
好的

Regards,

ty

在 2017年8月4日 下午10:34，Jackson Tian <notifications@github.com>写道：
